### ISSUE TITLE
升级1.04之后，I18n无效了

### ISSUE THREAD

**Issue by bloodxia** [masastack/BlazorComponent#472]
设置I18n的语言之后，并不生效，1.02是好的，不知道又是哪里出问题了。每次更新都引出一堆的其他bug，无语。

**Comment by capdiem** [comment]
@bloodxia 抱歉~ 之前的i18n拿语言存在一些设置模糊的问题，删掉了从http头拿语言，删掉了内置的cookiestorage，所以也不会帮你去设把当前语言缓存到cookie。新版你需要在修改语言时手动设置cookie，在初始化时（MainLayout里）手动从cookie里读缓存的语言。
CookieStorage 请查看 https://github.com/masastack/MASA.Blazor.Pro/blob/main/Masa.Blazor.Pro/Global/CookieStorage.cs

**Comment by bloodxia** [comment]
这样也挺好的，提个建议，每次更新是否能有一个changelog？我还专门找了一圈，完全没有更新日志，都不知道更新了什么。

**Comment by capdiem** [comment]
@bloodxia https://github.com/masastack/MASA.Blazor/releases
